service: oServer

provider:
  name: aws
  runtime: dotnetcore2.0
  region: ap-south-1

package:
  artifact: bin/release/netcoreapp2.0/deploy-package.zip

functions:
  api:
    handler: oServer::oServer.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY